trigger:
- master

pool:
  vmImage: ubuntu-latest  

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-8-jdk  # Install JDK 8
    export JAVA_HOME_8_X64=/usr/lib/jvm/java-8-openjdk-amd64
    export PATH=$PATH:$JAVA_HOME_8_X64/bin
    java -version  # Verify Java version
  displayName: 'Set Up JDK 8'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
- task: CopyFiles@2
  inputs:
    Contents: '**/.war'
    TargetFolder: '$(build.artifactstagingdirectory)'