trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '1.8'
      addToPath: true

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
